# Partie 2 - Prédiction du nombre d'exacerbations

## 1. Importer les données

In [1]:
import polars as pl

In [2]:
data_path = './data/trainDataDC2.csv.gz'

In [3]:
df = pl.read_csv(data_path)
df.shape

(14575, 21)

In [4]:
df.head()

shape: (5, 21)
┌────────────┬───────────┬────────────┬────────────┬───┬────────┬────────┬────────────┬────────────┐
│ patid      ┆ index_age ┆ previous_a ┆ total_pre_ ┆ … ┆ drug_s ┆ female ┆ log_charge ┆ log_asthma │
│ ---        ┆ ---       ┆ sthma_drug ┆ index_cann ┆   ┆ ---    ┆ ---    ┆ s          ┆ _charge    │
│ i64        ┆ str       ┆ s          ┆ isters_365 ┆   ┆ str    ┆ str    ┆ ---        ┆ ---        │
│            ┆           ┆ ---        ┆ ---        ┆   ┆        ┆        ┆ str        ┆ str        │
│            ┆           ┆ str        ┆ str        ┆   ┆        ┆        ┆            ┆            │
╞════════════╪═══════════╪════════════╪════════════╪═══╪════════╪════════╪════════════╪════════════╡
│ 1073754155 ┆ 14        ┆ 1          ┆ 1          ┆ … ┆ 0      ┆ NA     ┆ 7.11050628 ┆ 5.38509121 │
│            ┆           ┆            ┆            ┆   ┆        ┆        ┆ 71         ┆ 53         │
│ 1073799394 ┆ NA        ┆ 1          ┆ 2          ┆ … ┆ 0      ┆ 0      ┆ 9.91790976 ┆ 3.80621794 │
│            ┆           ┆            ┆            ┆   ┆        ┆        ┆ 41         ┆ 65         │
│ 1073854918 ┆ 62        ┆ 1          ┆ NA         ┆ … ┆ 0      ┆ 0      ┆ 7.99438073 ┆ 4.59774267 │
│            ┆           ┆            ┆            ┆   ┆        ┆        ┆ 68         ┆ 02         │
│ 1073898249 ┆ NA        ┆ 1          ┆ 2          ┆ … ┆ 0      ┆ 1      ┆ 8.07828778 ┆ NA         │
│            ┆           ┆            ┆            ┆   ┆        ┆        ┆ 31         ┆            │
│ 1073913003 ┆ 40        ┆ 1          ┆ 1          ┆ … ┆ 0      ┆ 0      ┆ 7.16026683 ┆ 3.39417276 │
│            ┆           ┆            ┆            ┆   ┆        ┆        ┆ 24         ┆ 67         │
└────────────┴───────────┴────────────┴────────────┴───┴────────┴────────┴────────────┴────────────┘

In [5]:
df['patid'].n_unique()

14575

Notre objectif est de construire un *pipeline* de *machine learning* qui pourra fonctionner sur un fichier de même structure que ce fichier de données initial ("trainDataDC2.csv.gz") et qui donnera, en sortie, la prédiction du nombre d'exacerbations de l'asthme, pour chaque patient, dans l'année suivant le début du traitement (variable `post_index_exacerbations365`).

In [6]:
df['post_index_exacerbations365'].null_count()

0

In [7]:
print(
    "Fraction of patients with zero exacerbation: {0:.2%}".format(
        (df['post_index_exacerbations365'] == 0).sum() / df['post_index_exacerbations365'].len()
    )
)

Fraction of patients with zero exacerbation: 88.60%

La variable dépendante (que l'on veut prédire, *outcome*, *label*, *target*, notée $y$) est donc `post_index_exacerbations365`, qui prend des valeurs entières positives.

In [8]:
target = df['post_index_exacerbations365']

Dans une perspective de modélisation statistique, on pense à la **loi de Poisson**
(qui décrit le résultat d'un processus de comptage) :
$$
y \sim \mathrm{Poisson}(\lambda)
$$

* Paramètre $\lambda \in \;]0, +\infty[$
* Espérance $\lambda$
* Variance $\lambda$

$$
\ln(\lambda) = \beta_0 + \beta_1 x
$$

À cause du logarithme, on n'a pas une régression linéaire ordinaire ; on parle de
*generalized linear model (GLM)*.

Il s'agit alors d'estimer :

* $\beta_1$ : coefficient de régression
* $\beta_0$ : intercept (ordonnée à l'origine)

$$
\lambda = \mathrm{e}^{\beta_0 + \beta_1 x} = \mathrm{e}^{\beta_0} \; \mathrm{e}^{\beta_1 x}
$$

## 2. Partitionner les données

Nous commençons par partitionner (*split*) les données, afin d'entraîner (*train*) le modèle sur une partie des données, et de garder une autre partie des données pour tester (*test*) le modèle.

In [9]:
import sklearn as skl

### Séparer les *features* ($X$) et l'*outcome* ($y$)

In [10]:
df.columns

['patid',
 'index_age',
 'previous_asthma_drugs',
 'total_pre_index_cannisters_365',
 'post_index_exacerbations365',
 'pneumonia',
 'sinusitis',
 'acute_bronchitis',
 'acute_laryngitis',
 'upper_respiratory_infection',
 'gerd',
 'rhinitis',
 'adherence',
 'total_pre_index_charge',
 'pre_asthma_days',
 'pre_asthma_charge',
 'pre_asthma_pharma_charge',
 'drug_s',
 'female',
 'log_charges',
 'log_asthma_charge']

Comme dans la partie 1, nous considérons toutes les autres variables comme les caractéristiques (variables indépendantes, *features*, notées $X$), à l'exception de l'identifiant patient `patid` et les variables transformées `log_*`.

In [11]:
features = df.select([
 'index_age',
 'previous_asthma_drugs',
 'total_pre_index_cannisters_365',
 'pneumonia',
 'sinusitis',
 'acute_bronchitis',
 'acute_laryngitis',
 'upper_respiratory_infection',
 'gerd',
 'rhinitis',
 'adherence',
 'total_pre_index_charge',
 'pre_asthma_days',
 'pre_asthma_charge',
 'pre_asthma_pharma_charge',
 'drug_s',
 'female',
])

In [12]:
X_train, X_test, y_train, y_test = skl.model_selection.train_test_split(
    features,
    target,
    test_size=0.2,
    random_state=42,
)

On pourrait vouloir stratifier sur $y$ (`stratify=target`), comme il aurait été souhaitable de le faire dans le cas binaire, sauf qu'ici il y a des classes ($y = 12$ ou $y = 13$) qui ne contiennent qu'un seul membre...

In [13]:
import numpy as np

In [14]:
target.hist(bins=np.arange(target.max() + 1))

shape: (13, 3)
┌────────────┬──────────────┬───────┐
│ breakpoint ┆ category     ┆ count │
│ ---        ┆ ---          ┆ ---   │
│ f64        ┆ cat          ┆ u32   │
╞════════════╪══════════════╪═══════╡
│ 1.0        ┆ [0.0, 1.0]   ┆ 14118 │
│ 2.0        ┆ (1.0, 2.0]   ┆ 265   │
│ 3.0        ┆ (2.0, 3.0]   ┆ 95    │
│ 4.0        ┆ (3.0, 4.0]   ┆ 39    │
│ 5.0        ┆ (4.0, 5.0]   ┆ 24    │
│ …          ┆ …            ┆ …     │
│ 9.0        ┆ (8.0, 9.0]   ┆ 3     │
│ 10.0       ┆ (9.0, 10.0]  ┆ 2     │
│ 11.0       ┆ (10.0, 11.0] ┆ 0     │
│ 12.0       ┆ (11.0, 12.0] ┆ 1     │
│ 13.0       ┆ (12.0, 13.0] ┆ 1     │
└────────────┴──────────────┴───────┘

## 3. Préparer les données

### Extraire les *features*

Comme nous l'avons déjà vu, notre jeu de données contient des *features* de types hétérogènes. Nous voulons normaliser (centrer et adimensionner) les variables numériques et encoder *one-hot* les variables catégorielles.

In [15]:
X_train.head()

shape: (5, 17)
┌───────────┬─────────────┬────────────┬───────────┬───┬────────────┬────────────┬────────┬────────┐
│ index_age ┆ previous_as ┆ total_pre_ ┆ pneumonia ┆ … ┆ pre_asthma ┆ pre_asthma ┆ drug_s ┆ female │
│ ---       ┆ thma_drugs  ┆ index_cann ┆ ---       ┆   ┆ _charge    ┆ _pharma_ch ┆ ---    ┆ ---    │
│ str       ┆ ---         ┆ isters_365 ┆ str       ┆   ┆ ---        ┆ arge       ┆ str    ┆ str    │
│           ┆ str         ┆ ---        ┆           ┆   ┆ str        ┆ ---        ┆        ┆        │
│           ┆             ┆ str        ┆           ┆   ┆            ┆ str        ┆        ┆        │
╞═══════════╪═════════════╪════════════╪═══════════╪═══╪════════════╪════════════╪════════╪════════╡
│ 18        ┆ 1           ┆ NA         ┆ 0         ┆ … ┆ 883        ┆ 1007.78    ┆ 1      ┆ 1      │
│ 21        ┆ 1           ┆ 1          ┆ 0         ┆ … ┆ 362        ┆ 21.41      ┆ 0      ┆ 0      │
│ 53        ┆ 1           ┆ 0          ┆ 1         ┆ … ┆ 0          ┆ 225.82     ┆ 0      ┆ 1      │
│ 31        ┆ 1           ┆ NA         ┆ 0         ┆ … ┆ 0          ┆ 21.41      ┆ 0      ┆ 0      │
│ 55        ┆ NA          ┆ 1          ┆ NA        ┆ … ┆ 0          ┆ 21.41      ┆ 0      ┆ 0      │
└───────────┴─────────────┴────────────┴───────────┴───┴────────────┴────────────┴────────┴────────┘

In [16]:
categorical_features = [
 'previous_asthma_drugs',
 'pneumonia',
 'sinusitis',
 'acute_bronchitis',
 'acute_laryngitis',
 'upper_respiratory_infection',
 'gerd',
 'rhinitis',
 'drug_s',
 'female',
]

In [17]:
encoder = skl.preprocessing.OneHotEncoder()

In [18]:
encoder.fit(X_train.select(categorical_features))  # fit encoder to categorical features

OneHotEncoder()

In [19]:
encoder.categories_

[array(['1', 'NA'], dtype=object),
 array(['0', '1', 'NA'], dtype=object),
 array(['0', '1', 'NA'], dtype=object),
 array(['0', '1', 'NA'], dtype=object),
 array(['0', '1', 'NA'], dtype=object),
 array(['0', '1', 'NA'], dtype=object),
 array(['0', '1', 'NA'], dtype=object),
 array(['0', '1', 'NA'], dtype=object),
 array(['0', '1', 'NA'], dtype=object),
 array(['0', '1', 'NA'], dtype=object)]

In [20]:
encoder.feature_names_in_

array(['previous_asthma_drugs', 'pneumonia', 'sinusitis',
       'acute_bronchitis', 'acute_laryngitis',
       'upper_respiratory_infection', 'gerd', 'rhinitis', 'drug_s',
       'female'], dtype=object)

Passons aux variables numériques (quantitatives).

In [21]:
numeric_features_int = [
 'index_age',
 'total_pre_index_cannisters_365',
 'pre_asthma_days',
 'pre_asthma_charge',
]

In [22]:
numeric_features_float = [
 'adherence',
 'total_pre_index_charge',
 'pre_asthma_pharma_charge',
]

In [23]:
assert (
    len(categorical_features) +
    len(numeric_features_int) +
    len(numeric_features_float) == len(features.columns)
)

In [24]:
scaler = skl.preprocessing.StandardScaler()

In [25]:
X_train_float = X_train.select(
    numeric_features_float
).cast(
    pl.Float64, strict=False
)

In [26]:
scaler.fit(X_train_float)  # compute mean and std to be used for later scaling

StandardScaler()

In [27]:
scaler.feature_names_in_

array(['adherence', 'total_pre_index_charge', 'pre_asthma_pharma_charge'],
      dtype=object)

In [28]:
float_transformer = skl.pipeline.Pipeline(  # sequence of data transformers
    steps=[
        # add conversion to float64,
        ('scaler', skl.preprocessing.StandardScaler()),
        # another preprocessing step
    ]
)

int_transformer = skl.pipeline.Pipeline(
    steps=[
        ('scaler', skl.preprocessing.StandardScaler()),
    ]
)

categorical_transformer = skl.pipeline.Pipeline(
    steps=[
        ('encoder', skl.preprocessing.OneHotEncoder()),
    ]
)

In [29]:
def cast_numeric_int(s):  # user-defined function
    return s.cast(pl.Int64, strict=False)

In [30]:
# construct a data transformer from a user-defined function
cast_int_transformer = skl.preprocessing.FunctionTransformer(cast_numeric_int)

In [31]:
int_transformer = skl.pipeline.Pipeline(
    steps=[
        ('caster', cast_int_transformer),
        ('scaler', skl.preprocessing.StandardScaler()),
    ]
)

In [32]:
def cast_numeric_float(s):
    return s.cast(pl.Float64, strict=False)

cast_float_transformer = skl.preprocessing.FunctionTransformer(cast_numeric_float)

float_transformer = skl.pipeline.Pipeline(
    steps=[
        ('caster', cast_float_transformer),
        ('scaler', skl.preprocessing.StandardScaler()),
    ]
)

In [33]:
preprocessor = skl.compose.ColumnTransformer(  # apply transformers to columns
    transformers=[
        ('num_float', float_transformer, numeric_features_float),
        ('num_int', int_transformer, numeric_features_int),
        ('cat', categorical_transformer, categorical_features),
    ]
)

In [34]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('num_float',
                                 Pipeline(steps=[('caster',
                                                  FunctionTransformer(func=<function cast_numeric_float at 0x7fdc5e06f480>)),
                                                 ('scaler', StandardScaler())]),
                                 ['adherence', 'total_pre_index_charge',
                                  'pre_asthma_pharma_charge']),
                                ('num_int',
                                 Pipeline(steps=[('caster',
                                                  FunctionTransformer(func=<function cast_numeric_int at 0x7fdd15727480>)),
                                                 ('scaler', StandardScaler())]),
                                 ['index_age', 'total_pre_index_cannisters_365',
                                  'pre_asthma_days', 'pre_asthma_charge']),
                                ('cat',
                                 Pipeline(steps=[('encoder', OneHotEncoder())]),
                                 ['previous_asthma_drugs', 'pneumonia',
                                  'sinusitis', 'acute_bronchitis',
                                  'acute_laryngitis',
                                  'upper_respiratory_infection', 'gerd',
                                  'rhinitis', 'drug_s', 'female'])])

Cet estimateur permet de transformer séparément différentes colonnes des données d'entrée. Les *features* ainsi générées sont alors concaténées pour former un seul *feature space*.

In [35]:
preprocessor.fit_transform(X_train)

array([[ 1.05303977,  0.29940817,  1.71832217, ...,  0.        ,
         1.        ,  0.        ],
       [-0.73360197, -0.26252957, -0.49997531, ...,  1.        ,
         0.        ,  0.        ],
       [ 1.90494841, -0.29713552, -0.0402673 , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.36680797,  0.09351425, -0.32876269, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.05303977, -0.33332881,  0.14072825, ...,  0.        ,
         1.        ,  0.        ],
       [-0.36680797, -0.36040896, -0.49997531, ...,  0.        ,
         0.        ,  1.        ]], shape=(11660, 36))

La variable d'*outcome* doit-elle être normalisée ?

In [36]:
y_train.shape

(11660,)

In [37]:
y_train.mean()

0.16818181818181818

In [38]:
y_train.median()

0.0

In [39]:
y_train.sum()

1961

## 4. Construire un modèle de prédiction

Ajoutons un modèle prédictif à notre *pipeline*.

In [40]:
pr = skl.linear_model.PoissonRegressor()

In [41]:
X_toy = np.array([[0, 0, 0],
                  [0, 0, 1],
                  [0, 1, 1],
                  [1, 1, 1]])
y_toy = np.array([1, 2, 3, 4])

In [42]:
pr.fit(X_toy, y_toy)

PoissonRegressor()

In [43]:
pr.score(X_toy, y_toy)  # accuracy

np.float64(0.7236112218520164)

In [44]:
pr.predict(np.array([[0, 0, 0], [0, 0, 1]]))

array([1.78408827, 2.17042105])

In [45]:
pr.coef_

array([0.17743707, 0.23860143, 0.19601367])

In [46]:
pr.intercept_

np.float64(0.5789075118990583)

In [47]:
pr.predict(np.array([[1, 1, 1], [0, 2, 3]]))

array([3.29023726, 5.17661502])

In [48]:
dummy = skl.pipeline.Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('regressor', skl.dummy.DummyRegressor(strategy='mean')),
    ]
)

In [49]:
dummy.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num_float',
                                                  Pipeline(steps=[('caster',
                                                                   FunctionTransformer(func=<function cast_numeric_float at 0x7fdc5e06f480>)),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['adherence',
                                                   'total_pre_index_charge',
                                                   'pre_asthma_pharma_charge']),
                                                 ('num_int',
                                                  Pipeline(steps=[('caster',
                                                                   FunctionTransformer(func=<function cast_nu...
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['index_age',
                                                   'total_pre_index_cannisters_365',
                                                   'pre_asthma_days',
                                                   'pre_asthma_charge']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder())]),
                                                  ['previous_asthma_drugs',
                                                   'pneumonia', 'sinusitis',
                                                   'acute_bronchitis',
                                                   'acute_laryngitis',
                                                   'upper_respiratory_infection',
                                                   'gerd', 'rhinitis', 'drug_s',
                                                   'female'])])),
                ('regressor', DummyRegressor())])

Il faut faire mieux que le modèle de régression *dummy* !

In [50]:
reg = skl.pipeline.Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('regressor', pr),
    ]
)

# reg.fit(X_train, y_train)
# ValueError: Input X contains NaN.
# PoissonRegressor does not accept missing values encoded as NaN natively.
# For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier
# and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible
# to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples
# with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of
# all estimators that handle NaN values at the following page:
# https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Pour utiliser la régression de Poisson, il nous faut remplacer les valeurs numériques manquantes par des valeurs moyennes, médianes ou constantes, etc. (*impute*).

### Exercice possible

Envisager de filtrer (*filter out*) les patients qui ont ("trop" ?) de valeurs manquantes ?

In [51]:
float_transformer = skl.pipeline.Pipeline(  # sequence of data transformers
    steps=[
        ('caster', cast_float_transformer),
        ('imputer', skl.impute.SimpleImputer()),
        ('scaler', skl.preprocessing.StandardScaler()),
    ]
)

int_transformer = skl.pipeline.Pipeline(
    steps=[
        ('caster', cast_int_transformer),
        ('imputer', skl.impute.SimpleImputer()),
        ('scaler', skl.preprocessing.StandardScaler()),
    ]
)

In [52]:
preprocessor = skl.compose.ColumnTransformer(  # apply transformers to columns
    transformers=[
        ('num_float', float_transformer, numeric_features_float),
        ('num_int', int_transformer, numeric_features_int),
        ('cat', categorical_transformer, categorical_features),
    ]
)

In [53]:
reg = skl.pipeline.Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('regressor', pr),
    ]
)

## 5. Entraîner le modèle

In [54]:
reg.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num_float',
                                                  Pipeline(steps=[('caster',
                                                                   FunctionTransformer(func=<function cast_numeric_float at 0x7fdc5e06f480>)),
                                                                  ('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['adherence',
                                                   'total_pre_index_charge',
                                                   'pre_asthma_pharma_charge']),
                                                 ('num_int',
                                                  Pipeline(steps=[('caster',
                                                                   FunctionTrans...
                                                                   StandardScaler())]),
                                                  ['index_age',
                                                   'total_pre_index_cannisters_365',
                                                   'pre_asthma_days',
                                                   'pre_asthma_charge']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OneHotEncoder())]),
                                                  ['previous_asthma_drugs',
                                                   'pneumonia', 'sinusitis',
                                                   'acute_bronchitis',
                                                   'acute_laryngitis',
                                                   'upper_respiratory_infection',
                                                   'gerd', 'rhinitis', 'drug_s',
                                                   'female'])])),
                ('regressor', PoissonRegressor())])

### Exercice possible

Explorer l'utilisation du paramètre `sample_weight`.

Utilisons ce modèle entraîné pour prédire les *outcomes* du jeu de test.

In [55]:
y_pred = reg.predict(X_test)

In [56]:
y_pred.min()

np.float64(0.13943624996146195)

In [57]:
y_pred.max()

np.float64(0.24559451580398856)

In [58]:
y_pred.mean()

np.float64(0.16818469094280933)

In [59]:
y_test.mean()

0.20308747855917667

In [60]:
y_pred.sum()

np.float64(490.2583740982892)

In [61]:
y_test.sum()

592

## 6. Évaluer le modèle

In [62]:
skl.metrics.mean_poisson_deviance(y_test, y_pred)

0.9483154871959726